#!/bin/bash
alias ls='ls --color'
ulimit -s 32768
export PATH=$PATH:$HOME/bin/

function cd(){
    command cd $*
    ls
}

function ojd(){
    if [ -e 'test' ];then
        rm -r 'test'
    fi
    echo $* > .problem_url
    oj d $*
}

function ojs(){
    if [ ! -e .problem_url ]; then
        echo Please download via ojd!
        exit 1
    fi
    oj s `cat .problem_url` main.cpp
}

function ojsc(){
    if [ ! -e .problem_url ]; then
        echo Please download via ojd!
        exit 1
    fi
    cat header.lisp main.lisp > submit.lisp
    oj s `cat .problem_url` submit.lisp
}


function ojt(){
    make
    oj t
}

function ojtd(){
    make debug
    oj t
}

function ojtc(){
    oj t -c "sbcl --script main.lisp"
}



my_tmp_dir="/tmp/mytmp/"
my_clip_file=$my_tmp_dir/clipboard

if [ ! -e $my_tmp_dir ]; then
    mkdir $my_tmp_dir
fi

function set-clip(){
    read val
    echo $val > $my_clip_file
}

function get-clip(){
    if [ ! -e $my_clip_file ];then
        echo Please use this after set-clip!
        return 1
    fi
    cat $my_clip_file
}

function catc(){
    cat $* | xsel --clipboard
}
