#!/usr/bin/env bash

./remove-files

names=`echo 'ABCDEFGHIJKLMNOPQRSTUVWXYZ' | fold -s1`

echo -e "#!/usr/bin/env bash \n make \n for i in *in \n do \n echo \$i \n ./a.out < \$i \n done" > test.sh
chmod u+x test.sh

read last

for name in $names
do
    mkdir $name
    cp main.cpp $name
    cp Makefile $name
    cp test.sh $name
    if [ "$name" == "$last" ]; then
        break
    fi
done

rm test.sh
